### ISSUE TITLE
HTTP and App Transport Security policy

### ISSUE THREAD

**Issue by butako** [MartinPham/FindMySync#13]
Hi folks,

After a fresh install of the app and following the posted instructions, setting my endpoint to a plain HTTP connection, I am getting this error in the app status panel:

'Data error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.'

I believe MacOS wants it to use HTTPS. However the example in the instructions shows plain HTTP and my HA service is running on plain HTTP too. Any idea how to tell the Mac it's OK to use HTTP please?

**Comment by butako** [comment]
OK, I got it working. I had to edit the file "info.plist" inside the application contents, adding these lines:

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

This was described here: https://developer.apple.com/forums/thread/22131 
It may not be most secure as it apparently turns off ATS but hey, works.

**Comment by MartinPham** [comment]
Thanks! I’ve added it in the latest build
