### ISSUE TITLE
Which device is which

### ISSUE THREAD

**Issue by ikolsteren** [MartinPham/FindMySync#3]
Is there a way that we can identify which device is which.   Just setup and got 9 devices synced over and not sure if there is a way that I can identify which is which.

**Comment by MartinPham** [comment]
I've updated! Please try the latest version

**Comment by ikolsteren** [comment]
Perfect - they are showing on the Mac side.   Home Assistant is still off but I didn't spend time to look to much at that.   Might be a delete them and get them added again.   Great little app though thank you :-)

**Comment by MartinPham** [comment]
You can try the Generate config option, so it will generate known_devices.yaml contents for you, with device names and id

<img width="748" alt="image" src="https://user-images.githubusercontent.com/2064515/213002488-10fc1720-6300-4cfe-b8a5-6a351d8e1733.png">

**Comment by ikolsteren** [comment]
Copied that over and looks good -
