### ISSUE TITLE
Battery draining

### ISSUE THREAD

**Issue by TychoWerner** [MartinPham/FindMySync#4]
Hi, yesterday I've installed FindMySync on my Macbook.
Leaving it with around 30% in the evening, arriving to my device in the morning it was completely dead.
I normally do this and it would've only drained a few %.

You can view the graphs below with activity bars.
I hope you are willing to look into this case.
<img width="505" alt="Scherm­afbeelding 2023-01-21 om 08 09 06" src="https://user-images.githubusercontent.com/34608981/213848293-3f55c282-c005-4b81-81c5-2203e9081ec6.png">

**Comment by MartinPham** [comment]
thanks for your report. 
could you try to change the interval time to higher? like 30 mins?
