### ISSUE TITLE
Compatibility for older mac's

### ISSUE THREAD

**Issue by davidrustingha** [MartinPham/FindMySync#5]
Would it be possible to have compatibility with for example MacOS Catalina? I have a MacOS VM running and the app only works on Monterey and higher, while my Apple ID login only works for Catalina (because of hardware/Apple limitations)

**Comment by MartinPham** [comment]
Good point, let me try to add compatibility

**Comment by honkerst** [comment]
Just another 2c in from a Big Sur user. Would be great if it worked with a couple of earlier OSes! Cheers!

**Comment by j3tang** [comment]
Count me in for this as well on Catalina. Seems like the perfect fit for use on an older machine to keep running.

**Comment by MartinPham** [comment]
Sorry for late response. The bigsur and catalina backport took longer time than I thought. Could you guys please try the latest build? Thanks!

https://github.com/MartinPham/FindMySync/releases/tag/latest

**Comment by honkerst** [comment]
When I click the 'Generate Home Assistant config' it shows my a sample known_devices.yaml in the 'status' window, but it's not the same as the code it inserts into known_devices.yaml. I'd fix it myself but I cannot select the text in the status window to copy it. 

My status window:
<img width="748" alt="Screenshot 2023-06-08 at 10 34 48" src="https://github.com/MartinPham/FindMySync/assets/43205559/424485f7-4893-4432-a1b2-81e61adb0a0b">

My known_devices.yaml
<img width="492" alt="Screenshot 2023-06-08 at 10 34 55" src="https://github.com/MartinPham/FindMySync/assets/43205559/0e0b091c-c7ca-45a4-8704-e0f598304db8">

**Comment by MartinPham** [comment]
thanks, the latest build will enable text selection. I've moved the generated config to Extras menu also
